### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by santiagoahc** [Bo887/Event_Detection#1]
Hi there!

I am really interested in the project. I would like to try to reproduce your results but I can't find the weights for the yellow cards neither the model used.

Could you re-upload the links?

thank you.

**Comment by Bo887** [comment]
@santiagoahc The model used is the generic darknet tiny yolo model. The weights are located in this [folder](https://github.com/CS196Illinois/Event_Detection/tree/master/darknet/backup) (the number in the filename indicates how many epochs the weights were generated.

**Comment by santiagoahc** [comment]
Hi boo887, thanks for answering. It looks like the folder's link was closed (is not working). I was wondering if you have the dataset you used for training the yellow card classification so I can train it myself.

**Comment by Bo887** [comment]
@santiagoahc The correct link is [here](https://github.com/Bo887/Event_Detection/tree/master/darknet/backup).

I'll let you know if I find the dataset we used.
